/*******************************************************************************
 * This file is part of the Appliance Energy Detector, a free household appliance energy disaggregation intelligence engine and webapp.
 * 
 * Copyright (C) 2011,2012 Taylor Raack <traack@raack.info>
 * 
 * The Appliance Energy Detector is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * The Appliance Energy Detector is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with the Appliance Energy Detector.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * According to sec. 7 of the GNU Affero General Public License, version 3, the terms of the AGPL are supplemented with the following terms:
 * 
 * If you modify this Program, or any covered work, by linking or combining it with any of the following programs (or modified versions of those libraries), containing parts covered by the terms of those libraries licenses, the licensors of this Program grant you additional permission to convey the resulting work:
 * 
 * Javabeans(TM) Activation Framework 1.1 (activation) - Common Development and Distribution License Version 1.0
 * AspectJ 1.6.9 (aspectjrt and aspectjweaver) - Eclipse Public License 1.0
 * EMMA 2.0.5312 (emma and emma_ant) - Common Public License Version 1.0
 * JAXB Project Libraries 2.2.2 (jaxb-api, jaxb-impl, jaxb-xjc) - Common Development and Distribution License Version 1.0
 * Java Standard Template Library 1.2 (jstl) - Common Development and Distribution License Version 1.0
 * Java Servlet Pages API 2.1 (jsp-api) - Common Development and Distribution License Version 1.0
 * Java Transaction API 1.1 (jta) - Common Development and Distribution License Version 1.0
 * JavaMail(TM) 1.4.1 (mail) - Common Development and Distribution License Version 1.0
 * XML Pull Parser 3 (xpp3) - Indiana University Extreme! Lab Software License Version 1.1.1
 * 
 * The interactive user interface of the software display an attribution notice containing the phrase "Appliance Energy Detector". Interactive user interfaces of unmodified and modified versions must display Appropriate Legal Notices according to sec. 5 of the GNU Affero General Public License, version 3, when you propagate an unmodified or modified version of the Program. In accordance with sec. 7 b) of the GNU Affero General Public License, version 3, these Appropriate Legal Notices must prominently display either a) "Initial Development by <a href='http://www.linkedin.com/in/taylorraack'>Taylor Raack</a>" if displayed in a web browser or b) "Initial Development by Taylor Raack (http://www.linkedin.com/in/taylorraack)" if displayed otherwise.
 ******************************************************************************/
package info.raack.appliancelabeler.service;

import info.raack.appliancelabeler.model.AlgorithmPredictions;
import info.raack.appliancelabeler.model.EnergyTimestep;
import info.raack.appliancelabeler.model.StepgreenUserDetails;
import info.raack.appliancelabeler.model.UserAppliance;
import info.raack.appliancelabeler.model.appliancestatetransition.ApplianceStateTransition;
import info.raack.appliancelabeler.model.energymonitor.EnergyMonitor;
import info.raack.appliancelabeler.security.OAuthData;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.springframework.security.oauth.consumer.token.OAuthConsumerToken;

import edu.cmu.hcii.stepgreen.data.ted.data.SecondData;
import edu.cmu.hcii.stepgreen.data.teds.Ted5000;

public interface DataService {
	
	public enum LabelResult {OK,NO_POWER_INCREASE,NO_POWER_DECREASE,NOT_TURNED_OFF};
	
	public enum DataFrequency {SECONDS, MINUTES, HOURS, DAYS, MONTHS};

	public List<Ted5000> getTEDIdsForUserId(String userId, boolean needContext);
	public StepgreenUserDetails getStepgreenUserInfo();
	public long getLastDatapoint(EnergyMonitor energyMonitor);
	public Map<String, OAuthConsumerToken> getOAuthTokensForUserId(String userId);
	
	/**
	 * Creates an on/off label pair for the specific user appliance at the current energy monitor dates. The labels will be marked as being generated by a user, not an algorithm.
	 * 
	 * @param monitor the energy monitor for the user appliance
	 * @param userApplianceId the user appliance id
	 * @param onTime a time indicating when the on label should be created
	 * @param offTIme a time indicating when the off label should be created
	 * @param force should the training points be added even if the appliance was not detected to have been turned on and off
	 */
	public LabelResult createUserGeneratedLabelsForUserApplianceId(EnergyMonitor monitor, int userApplianceId, Date onTime, Date offTime, boolean force);
	public void createUserGeneratedLabelsSurroundingAnonymousTransition(int transitionid, int userApplianceId);
	
	public Map<UserAppliance, List<ApplianceStateTransition>> getPredictedApplianceStateTransitionsForMonitor(EnergyMonitor energyMonitor, int algorithmId, Date start, Date end);
	public Map<UserAppliance,List<EnergyTimestep>> getApplianceEnergyConsumptionForMonitor(EnergyMonitor energyMonitor, int algorithmId, Date start, Date end);
	
	public void saveOAuthTokensForUserId(String userId, String email, Map<String, OAuthConsumerToken> tokens);
	public void storeDataAndAlgorithmPredictions(EnergyMonitor energyMonitor, List<SecondData> data, long l, Map<Integer, AlgorithmPredictions> algorithmPredictions);
	
	public void runInTransaction(Runnable runnable);
	public OAuthData getOAuthDataForUserId(String userId);
}
